# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import order_pb2 as order__pb2


class OrderPricerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetOrderPrice = channel.unary_unary(
                '/pizza.OrderPricer/GetOrderPrice',
                request_serializer=order__pb2.PizzaOrder.SerializeToString,
                response_deserializer=order__pb2.PizzaOrderPriced.FromString,
                )


class OrderPricerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetOrderPrice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrderPricerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetOrderPrice': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrderPrice,
                    request_deserializer=order__pb2.PizzaOrder.FromString,
                    response_serializer=order__pb2.PizzaOrderPriced.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pizza.OrderPricer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class OrderPricer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetOrderPrice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pizza.OrderPricer/GetOrderPrice',
            order__pb2.PizzaOrder.SerializeToString,
            order__pb2.PizzaOrderPriced.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
